
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: timeout_fallback
          uri: http://localhost:4001
          predicates:
            - Path=/fallback
        - id: circuitbreaker_route
          uri: http://localhost:4001
          predicates:
            - Path=/a/**
          filters:
            - name: CircuitBreaker
              args:
                name: c1
                fallbackUri: forward:/fallback
        - id: local
          uri: forward:/localhost:4001/fallback
          predicates:
            - Path=/local


resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      slowCallDurationThreshold: 5s
      slowCallRateThreshold: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.IllegalStateException
  instances:
    c1:
      baseConfig: default
      slowCallDurationThreshold: 1s
    c2:
      baseConfig: default
      slowCallDurationThreshold: 2s

server:
  port: 8044
